version: '3.8'

services:
  # Test service
  tests:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        NODE_ENV: test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@test-db:5432/app_test
      - REDIS_URL=redis://test-redis:6379
      - CUSTOMER_ID=test
    depends_on:
      - test-db
      - test-redis
    command: npm test

  # Test database service
  test-db:
    image: postgres:14-alpine
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_test
    tmpfs:
      - /var/lib/postgresql/data

  # Test Redis service
  test-redis:
    image: redis:7-alpine
    tmpfs:
      - /data

volumes:
  node_modules: 