site_name: SaaS Pipeline Documentation
site_description: Documentation for the SaaS Pipeline system with MermaidFlow integration and user-specific AI assistants
site_author: Pipeline Team

# Repository
repo_name: pipeline
repo_url: https://github.com/yourusername/pipeline

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - search.highlight
    - search.share

# Extensions
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji

# Page tree
nav:
  - Home: index.md
  - Architecture:
    - MVP Architecture: mvp-architecture.md
    - Enterprise Architecture: enterprise-architecture.md
  - Business:
    - Business Model: business-model.md 